Ig2 122 wc ustalenie rankingu
kwojtow/io-grupa-a pull request #57
Opened 2022-05-31 23:21 UTC by Wotaker

- Nowy endpoint playerWon(id, user) [Post /id/state/user]. Markuje zadanego gracza jako wygranoego, gdy frontend zasygnalizuje wygraną rozgrywki.

- Gdy zakończy się gra i jest ona usuwana endGame(id) [Delete /id/state] → GameService.endGame(id), iterujemy po liście graczy, i dla wygranego aktualizujemy punkty rankingowe.

- Punkty rankingowe aktualizyjemy według zmodyfikowanego softmax.

2022-06-02 08:34 UTC, Wotaker reviewed
Do Poprawy, usunąć niepotrzebny endpoint, zaczekać na merge [PR#56 Asi](IG2-129-JB-zakonczenie-gry), wtedy zmodyfikować

2022-06-02 08:34 UTC, Wotaker commented on io-backend/src/main/java/agh/io/iobackend/controller/GameController.java
> +    @PostMapping("/{id}/state/{user}")
NIEPOTRZEBNE, [PR Asi](IG2-129-JB-zakonczenie-gry) rozwiązuje tą sprawe. Do poprawy

2022-06-02 08:54 UTC, Sirtus requested changes
Do poprawy

2022-06-11 16:20 UTC, Wotaker commented on io-backend/src/main/java/agh/io/iobackend/controller/GameController.java
> +    @PostMapping("/{id}/state/{user}")
Dobra, zapomniałem już tego usunąć przy commitcie, ale działa więc już tak zostawie pls, nie chce mi się już tego zmieniać

2022-06-11 16:55 UTC, Sirtus approved these changes

2022-06-13 20:36 UTC, merged